'use strict';
(async()=>{
 const config=await fetch('locale-config.json?v=r12',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(r.status);return r.json();});
 const grid=document.getElementById('gallery'),dialog=document.getElementById('lightbox'),viewer=document.getElementById('viewer'),picker=document.getElementById('locale-picker');let frames=[],active=0,opener;
 document.getElementById('revision').textContent=config.version;
 for(const locale of config.locales){const option=document.createElement('option');option.value=locale.code;option.textContent=locale.label;picker.append(option);}
 const setZoom=on=>{viewer.classList.toggle('zoomed',on);document.getElementById('zoom').setAttribute('aria-pressed',String(on));document.getElementById('zoom').textContent=on?'Fit to view':'Zoom 100%';};
 function show(index){active=(index+frames.length)%frames.length;const f=frames[active],img=document.getElementById('full-image');img.src=f.preview;img.alt=f.headline.join(' ');document.getElementById('modal-title').textContent=f.localeName+' · '+f.slot;document.getElementById('download').href=f.preview;setZoom(false);viewer.scrollTo(0,0);}
 async function selectLocale(code,updateUrl=true){const locale=config.locales.find(l=>l.code===code)||config.locales.find(l=>l.code===config.defaultLocale);picker.value=locale.code;document.documentElement.lang=locale.lang;document.documentElement.dir=locale.dir;const data=await fetch(locale.data+'?v=r12',{cache:'no-store'}).then(r=>r.json());frames=data.frames;grid.replaceChildren();document.getElementById('locale-status').textContent=locale.label+' · '+data.status;
  frames.forEach((f,i)=>{const figure=document.createElement('figure');figure.className='frame';const button=document.createElement('button');button.setAttribute('aria-label','Open '+f.slot+': '+f.headline.join(' '));const img=document.createElement('img');img.src=f.preview;img.alt=f.headline.join(' ');img.width=440;img.height=956;button.append(img);button.onclick=()=>{opener=button;show(i);dialog.showModal();document.getElementById('close').focus();};const cap=document.createElement('figcaption');cap.textContent=f.slot;const label=document.createElement('span');label.textContent=f.locale+' · '+f.revision;cap.append(label);figure.append(button,cap);grid.append(figure);});
  await Promise.all([...grid.querySelectorAll('img')].map(i=>i.decode()));if(updateUrl){const u=new URL(location.href);u.searchParams.set('v',config.version);u.searchParams.set('locale',locale.code);history.replaceState(null,'',u);}window.galleryReady=true;}
 picker.onchange=()=>selectLocale(picker.value);await selectLocale(new URLSearchParams(location.search).get('locale')||config.defaultLocale,false);
 document.getElementById('previous').onclick=()=>show(active-1);document.getElementById('next').onclick=()=>show(active+1);document.getElementById('close').onclick=()=>dialog.close();document.getElementById('zoom').onclick=()=>setZoom(!viewer.classList.contains('zoomed'));dialog.addEventListener('close',()=>opener?.focus());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')show(active-1);if(e.key==='ArrowRight')show(active+1);});
})().catch(error=>{document.getElementById('load-error').hidden=false;console.error(error);});
